main: main.Main
name: PLteste
author: loolsd
version: 1.0
commands:
  TPR:
    description: L d+
    usage: /TPR
  GM:
    description: L d+
    usage: /GM
  INV:
    description: l d+
    usage: /INV
  HAT:
    description: l d+
    usage: /HAT
  FLY:
    description: l d+
    usage: /fly 
